# --- Переменные конфигурации кластера (не секреты) ---
talos_cluster_name: "talos-cluster-test"
talos_interface_vip: "10.10.61.50"
talos_controlplane_endpoint: "https://10.10.61.50:6443"

talos_cp_machine_additional_config:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - https://gitlab.okbtsp.corp:443
    config:
      gitlab.okbtsp.corp:
        auth:
          username: svc-oit-docker-registry-read
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            35333432326665323335323763663766383734316534636466633637653063393331613031373633
            6662653237643531323634343662306462363764646132370a663238373134636432346265663966
            33356139356330366664653461386663306136633962643665393461333735663762663362363565
            6635333164353937620a386662303265346465643866323731303062623962306661616135636636
            36303665616536346330373961613336663931643738613137653739343237353435

  time:
    disabled: false
    servers:
      - 10.10.10.3
      - 10.10.7.3

talos_cluster_network:
  cni:
    name: none
  podSubnets:
    - 10.224.0.0/13
  serviceSubnets:
    - 10.240.0.0/13

talos_cp_cluster_additional_config:
  inlineManifests:
    - name: cilium
      contents: |
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: cilium-install
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: cilium-install
          namespace: kube-system
        ---
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: cilium-install
          namespace: kube-system
        ---
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: cilium-install
          namespace: kube-system
        spec:
          backoffLimit: 10
          template:
            metadata:
              labels:
                app: cilium-install
            spec:
              restartPolicy: OnFailure
              tolerations:
                - operator: Exists
                - effect: NoSchedule
                  operator: Exists
                - effect: NoExecute
                  operator: Exists
                - effect: PreferNoSchedule
                  operator: Exists
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
                  effect: NoSchedule
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
                  effect: NoExecute
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
                  effect: PreferNoSchedule
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: node-role.kubernetes.io/control-plane
                            operator: Exists
              serviceAccount: cilium-install
              serviceAccountName: cilium-install
              hostNetwork: true
              containers:
              - name: cilium-install
                image: quay.io/cilium/cilium-cli:latest
                env:
                - name: KUBERNETES_SERVICE_HOST
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
                - name: KUBERNETES_SERVICE_PORT
                  value: "6443"
                command:
                  - cilium
                  - install
                  - --set
                  - ipam.mode=kubernetes
                  - --set
                  - kubeProxyReplacement=true
                  - --set
                  - securityContext.capabilities.ciliumAgent={CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}
                  - --set
                  - securityContext.capabilities.cleanCiliumState={NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}
                  - --set
                  - cgroup.autoMount.enabled=false
                  - --set
                  - cgroup.hostRoot=/sys/fs/cgroup
                  - --set
                  - k8sServiceHost=localhost
                  - --set
                  - k8sServicePort=7445
                  - --set
                  - hubble.enabled=true
                  - --set
                  - hubble.relay.enabled=true
                  - --set
                  - hubble.ui.enabled=true
                  - --set
                  - ipam.mode=kubernetes
                  - --set
                  - operator.replicas=1
