# --- Переменные конфигурации кластера (не секреты) ---
talos_controlplane_endpoint: "https://talos-cluster-test.okbtsp.corp:6443"
talos_controlplane_dns: "talos-cluster-test.okbtsp.corp"
talos_cluster_name: talos-cluster-test
talos_additional_cert_sans:
  - "{{talos_controlplane_dns}}"
  - "10.10.61.49"

talos_addons_clone: false
