- name: create folder for a group
  vmware.vmware.folder:
    hostname: "{{ s1_vcenter_hostname }}"
    username: "{{ s1_vcenter_username }}"
    password: "{{ s1_vcenter_password }}"
    validate_certs: "{{ s1_vcenter_validate_certs }}"
    datacenter: "{{ s1_vcenter_datacenter }}"
    relative_path: "{{s1_vcenter_parent_folder}}/{{ target }}"
    folder_type: vm
    state: present
  run_once: true
  when:
    - groups[target] is defined

- name: set folder for a group
  ansible.builtin.set_fact:
    s1_vcenter_folder_final: "{{s1_vcenter_parent_folder}}/{{target}}"
  when:
    - groups[target] is defined

- name: Debug — render template and save locally
  ansible.builtin.copy:
    content: "{{ lookup('template', 'controlplane.yaml.j2') }}"
    dest: "/tmp/{{ inventory_hostname }}_controlplane_debug.yaml"
  delegate_to: localhost
  run_once: true

- name: Debug — render template and save locally
  ansible.builtin.copy:
    content: "{{ lookup('template', 'worker.yaml.j2')  }}"
    dest: "/tmp/{{ inventory_hostname }}_worker.yaml"
  delegate_to: localhost
  run_once: true

- name: create VM
  community.vmware.vmware_guest:
    hostname: "{{ s1_vcenter_hostname }}"
    username: "{{ s1_vcenter_username }}"
    password: "{{ s1_vcenter_password }}"
    validate_certs: "{{ s1_vcenter_validate_certs }}"
    datacenter: "{{s1_vcenter_datacenter}}"
    cluster: "{{s1_vms_cluster}}"
    folder: "{{s1_vcenter_folder_final}}"
    disk: "{{s1_vms_disk}}"
    hardware: "{{s1_vms_hardware}}"
    resource_pool: "{{s1_vms_resource_pool}}"
    state: "{{s1_vms_state}}"
    template: "{{s1_vms_template}}"
    name: "{{inventory_hostname}}"
    vapp_properties:
      - id: talos.config
        value: "{{ (lookup('template', talos_node_type ~ '.yaml.j2') | b64encode).replace('\n', '') }}"
        type: string
  register: s1_create_VM
  async: 3600
  poll: 0

- name: Wait for creation to finish
  ansible.builtin.async_status:
    jid: "{{ s1_create_VM.ansible_job_id }}"
  delay: 5
  retries: 60
  register: s1_vm_creation_jobs
  until: s1_vm_creation_jobs.finished

- name: reconfigure VM networks
  community.vmware.vmware_guest:
    hostname: "{{ s1_vcenter_hostname }}"
    username: "{{ s1_vcenter_username }}"
    password: "{{ s1_vcenter_password }}"
    validate_certs: "{{ s1_vcenter_validate_certs }}"
    datacenter: "{{s1_vcenter_datacenter}}"
    cluster: "{{s1_vms_cluster}}"
    folder: "{{s1_vcenter_folder_final}}"
    disk: "{{s1_vms_disk}}"
    hardware: "{{s1_vms_hardware}}"
    networks: "{{s1_vm_network_config}}"
    resource_pool: "{{s1_vms_resource_pool}}"
    state: "{{s1_vms_state}}"
    template: "{{s1_vms_template}}"
    name: "{{inventory_hostname}}"
  register: s1_reconfig_VM
  async: 3600
  poll: 0

- name: Wait for config to finish
  ansible.builtin.async_status:
    jid: "{{ s1_reconfig_VM.ansible_job_id }}"
  delay: 5
  retries: 60
  register: s1_vm_reconfig_jobs
  until: s1_vm_reconfig_jobs.finished

- name: get vm state
  ansible.builtin.set_fact:
    s1_vm_id: "{{s1_vm_creation_jobs.instance.moid}}"
    s1_vm_state: "{{s1_vm_creation_jobs.instance.hw_power_status}}"
