apiVersion: v1alpha1
kind: TrustedRootsConfig
name: my-enterprise-ca
certificates: |
  -----BEGIN CERTIFICATE-----
  MIIDbjCCAlagAwIBAgIQRKuEGKkowJZIwHd1osrfRjANBgkqhkiG9w0BAQsFADA6
  MTgwNgYDVQQDEy9JbmZyYS5jb3JwIENsYXNzIDEgUm9vdCBDZXJ0aWZpY2F0aW9u
  IEF1dGhvcml0eTAeFw0yNDA1MzAxMzM3NTNaFw0zNDA1MzAxMzQ3NTNaMDoxODA2
  BgNVBAMTL0luZnJhLmNvcnAgQ2xhc3MgMSBSb290IENlcnRpZmljYXRpb24gQXV0
  aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAreLyQqDcH/9n
  t4JhEpylOEliH/+c/iUR1CKSpoJgc8XlCHf6iiHH4UFbF8mD3Rs2U8JtlbQHiL7m
  VeRlFqAzCSvdBS66+YPx4+xFKcMzjCxLsz26F1WIt0r6pM7eZWqJYc0OguM/LF9d
  kMNy027QLTxWuzv34IFHQnEv3DWFZruCumlxzwpfeQaRQsduxn+GoHsa4PwQAlYo
  4B2Lkferdd51JCGW5yW1uePqN30IXnADTresX+eAftvbUmSaVMPuQh1J2rXo8ihy
  v+ZM25VSSXBwopN9c6fPF7+9WSuQZFVOgG9/dCYIkUqiyNcqkUsRV69huMBAyozT
  b3/WVEpu2QIDAQABo3AwbjALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAd
  BgNVHQ4EFgQUn9vO2Z00whB7tjFUQFDAKHkJyk0wEAYJKwYBBAGCNxUBBAMCAQAw
  HQYDVR0gBBYwFDAGBgRVHSAAMAoGCCoDBIsvQ1kFMA0GCSqGSIb3DQEBCwUAA4IB
  AQBJ2VbmWJf6/dY//QNRVAGCVGll5RMvGkgqXYuKn+DLE+KjyXMtLAbx+/wxe175
  bZ0a95JBJLUQZsU+qLSP/pHrMDRH6U+v3kzcPtYdvkmXu/9FiqVoqN17uhsTNje6
  6rCHwwo+fYxFBszMV+bPnyKOmbuEhegjSD+VC8H/F/Ewb2/E4h4OScidmQM/vhlS
  aguc5kbh+6BlSma7mzQy5xfPiZjJc5w4EwTryrmdFMaWMV2leyNas23OaM/Q5xMU
  fxxte8MEMeIm1nwE1uQJ3d9T+sBbgoXH19Cv/C6ePhHn2GIWZoo8JDkG/MJwIth5
  mDdUtsH9nu/YiEApbxH14CLq
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFmjCCBIKgAwIBAgITYQAAAAUOw3naxQsWhQAAAAAABTANBgkqhkiG9w0BAQsF
  ADA6MTgwNgYDVQQDEy9JbmZyYS5jb3JwIENsYXNzIDEgUm9vdCBDZXJ0aWZpY2F0
  aW9uIEF1dGhvcml0eTAeFw0yNTAzMzExNDMyMDhaFw0zMDAzMzExNDQyMDhaMIGM
  MQswCQYDVQQGEwJCWTETMBEGA1UECBMKQmVsYXJ1c2lhbjEOMAwGA1UEBxMFTWlu
  c2sxDjAMBgNVBAoTBUlORlJBMQwwCgYDVQQLEwNPSVQxGzAZBgNVBAMTEks4c0NB
  Lm9rYnRzcC5sb2NhbDEdMBsGCSqGSIb3DQEJARYOb2l0QG9rYnRzcC5jb20wggEi
  MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDqUKASW9khaqt2CfdKzr1EZ4Mf
  cnSKUmpU57Nh/vaMYg9m0rj/k2OPRL96GzqrcNEq/CqwKmlN5HXVBwPU8D7xq2Mv
  +iswjFn3fB9rT4hDf0XmCaFGD4WiWLV1MLC/BvedeL3lONoWe9bPEJuj0RK/LnWA
  4nUl24B0aUfi96VYXQH+lu/ic61TbjZJ4RlhEvVoOBgfrfwJ2+1cnoFfq9C5dN81
  8LmQvAjN7MFKefPOEwaF3aqDbcBU+rP7WHlv/8hQs7l18/sCU6ISJ6dAd1itaByK
  hsU6Kp3eM/9GbFsZA7nHXxe+YVlHnsccflImMmedPDeOJsbc/LEE35PglROVAgMB
  AAGjggJEMIICQDAdBgNVHQ4EFgQUvVX8IDAHRzBXVSP5elBI1Fr8UwUwHwYDVR0j
  BBgwFoAUn9vO2Z00whB7tjFUQFDAKHkJyk0wgdIGA1UdHwSByjCBxzCBxKCBwaCB
  voZeaHR0cDovL3BraS5va2J0c3AubG9jYWwvQ2VydERhdGEvSW5mcmEuY29ycCUy
  MENsYXNzJTIwMSUyMFJvb3QlMjBDZXJ0aWZpY2F0aW9uJTIwQXV0aG9yaXR5LmNy
  bIZcaHR0cDovL3BraS5pbmZyYS5jb3JwL0NlcnREYXRhL0luZnJhLmNvcnAlMjBD
  bGFzcyUyMDElMjBSb290JTIwQ2VydGlmaWNhdGlvbiUyMEF1dGhvcml0eS5jcmww
  ge8GCCsGAQUFBwEBBIHiMIHfMHQGCCsGAQUFBzAChmhodHRwOi8vcGtpLm9rYnRz
  cC5sb2NhbC9DZXJ0RGF0YS9Sb290Q0EtMDFfSW5mcmEuY29ycCUyMENsYXNzJTIw
  MSUyMFJvb3QlMjBDZXJ0aWZpY2F0aW9uJTIwQXV0aG9yaXR5LmNydDBnBggrBgEF
  BQcwAoZbaHR0cDovcGtpLmluZnJhLmNvcnAvQ2VydERhdGEvUm9vdENBLTAxX0lu
  ZnJhLmNvcnAgQ2xhc3MgMSBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5LmNy
  dDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAPBgNVHRMBAf8EBTADAQH/MAsG
  A1UdDwQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAZLMaHDm2njW3I+eWX8glirtr
  BwdNay4ryraMA7WpznuWQbpTzefVgCPL3hcF4nZfGJ3s/dyTfNfeYkoA83atzuzG
  axTanxe405AvnJ5k8ZnAuNNk5LcnAjCRMktPpm23rON0AteGsp0z/sb5mt/B/W8O
  SEwTqMeqtNGK4ERwqWYaiX8nVNL5VfhCxKjl8i0izM5wG9VfpGEv8tJw43o6dxyc
  UkZNj82JOtWfsXtupxOB24Of1ZZ4FrAeD0Z+yy0glzvEIJkkrBv2UKdC/F1qg8BN
  YCkBiizmWNQifrLOph6GDIR0qIYwdSSfFnzrVrCyf93FkF3Hz3RPJmduqQN3Hw==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFCzCCAvOgAwIBAgIQKsmV2EfbSIVJh+mzZJSZZjANBgkqhkiG9w0BAQ0FADAY
  MRYwFAYDVQQDEw1Sb290Q0EtT0tCVFNQMB4XDTIwMDUxMjE0NTk1MVoXDTMwMDUx
  MjE1MDk1MFowGDEWMBQGA1UEAxMNUm9vdENBLU9LQlRTUDCCAiIwDQYJKoZIhvcN
  AQEBBQADggIPADCCAgoCggIBAOFDplFXYATsSwYlHyP+YLq4S48eEgCOgeDzu9pH
  N0sIPcZsrf0yPE/VgEf5PeuSAgZcFIfjJSBovfj/o6ABx3KQGQlPC2NAOTH6s31F
  cgnCf9+f5yNM7AYDMgFI3OjPF6DXwPmHbFpj5mtuAvADbWSdOftp6QwSLxvv1AZQ
  YRXScaCf4L65Jt8cjY64Dr7/RrSPtDBoPhX+xy+2Re4FNEf9lg6SMAjQLdkHpxt4
  z1wsMlNMddUi7gX2AzAic5M3GU6BVV+OXiNhVMWHiX0rebz0tJ+K14qTkgrOa39T
  qS1bxRbUOO7L5KRNG5sOlHSHdsNVuzM4EA/FTkphxDTh6DKkzeRLr9Zl1i9czbG/
  CfQyt7mtqazZSqewsEGa7BdVYuBl73cV2eFPI4M+JwGO6AHELe9rjcBFi5uHRZiJ
  Zyz4k57ISczkF4O/kJ9iIrXpG9aCd//7xxb3Mp2uCZKC+aZlHOuPDm3F9wh6oeBI
  2yrDp110nvPzSGmOybGLeOFaMjjBVup6dfU6OD1TfaNXxc2uPlvAz//9fJzP79LR
  rOdy4j/UrujjIuul08xOjvpBdjTwCbgF6798oPRwYU9wxDVMFmpqSIV7CgnYFxQu
  QMa9b1OT0vEB71X+NsnDQgoLgECHV2/Sao0ySqGRXcrWVtk1ydo4JcO9Byaayh9W
  sbudAgMBAAGjUTBPMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
  DgQWBBQXOoondibcee3zcSVIS46VFeEm1jAQBgkrBgEEAYI3FQEEAwIBADANBgkq
  hkiG9w0BAQ0FAAOCAgEAi53UPxRsLFVp9or6HS0QGHRwtUiBByU/qYUTCBRNpE3Q
  OWgQWtVDLkXHqee6TP7f0mgMd/MZcORAsYTRrEOxeNum0tve8ilk9faiHVISLztT
  veLAq8LV3z5n7nHM8UHhPeGTFBBIyOStYlyoWcbCtfX4BPeUvPaBAUxioSOd03kq
  DjQnkjoqrOdux4Tf2wqd4vFWM3jRH6kCDT4LrbgkTbquF+U4zNk7PgiSc70uqGn9
  hb7/xnTNTFeUZ5fma9R5vv0QP1S4zAgsZj3JKduD/eVkCUcwvJnMHjhdkLYaPR5f
  PS5/5FkenKKYLOQb50s3nHOsinnq+WpAEW2GW/rruwOoG88Nc4xT7TI6S7sEKKbh
  GJM6u8GSqwptDV1pU9AlBk23GH2dU1mS4dg1GaIY17zKzNRntzisXd4TyRzFWxz/
  UDaWquT1nMPGlsbFGSls7DgxKOSzc50ZrbwIElqPVD7WSoAj9sjgKw0QTSpv1PBa
  fJ1tjhCPXkjTxYWONUy2V36wZvr0T9EWCGru0W10pgnMZd891eP7FFTFl73jUXxm
  1AsiITMJJwpEyC7kJGCVwDCCxWXh/NnNspRuDDOKzpfHhExI81802wdfH22df+f5
  agfq9VHLObk/XWmmoOOKybisDGUuxhMiJ2vDgIBOprteaMeV2A9JW/cvgkYBlpg=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFxjCCA66gAwIBAgITEwAAAAfYBWHRqjIGSQAAAAAABzANBgkqhkiG9w0BAQ0F
  ADAYMRYwFAYDVQQDEw1Sb290Q0EtT0tCVFNQMB4XDTIzMDUxMTIwMTQxMVoXDTI2
  MDUxMTIwMjQxMVowUjESMBAGCgmSJomT8ixkARkWAmJ5MRYwFAYKCZImiZPyLGQB
  GRYGb2tidHNwMSQwIgYDVQQDExtva2J0c3AtU1JWLVNVQkNBLTAxLUNBLTIwMjMw
  ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKKggRtANu6NGp2RL1EYFz
  PEd+8T4dNbbwO3smJ5DZJT+CtNkNdq+N1BLhBJLAQYhueMYb84tTRsyUVarXRLuk
  7HrgwfbQH0aGrlbdU+ylCCYTXkcKQDzY2q0dORO5VsODI5qY5sVDnfxl+hZHvaFw
  4BqBU27z7iRFZT9eTb+mOYDLoXOP5jitqICwkjxSAg88c5orVsQW7+7/SolRu+9T
  mt1Io1aTT6MpzyEZlRkjEKwu9dHrwewsZvg9Ery1nq8lF2Q+gkJbEsgQhTMkIxuZ
  PN74IioXUP8R69H9rgPsuOn4s8c0IxOXgNrgaGow7mWelSuYfMmZabKDrWNMOptp
  AgMBAAGjggHNMIIByTAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUflZ69UDt
  N9Eays4exhDZ2HSwguQwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0P
  BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUFzqKJ3Ym3Hnt83El
  SEuOlRXhJtYwfwYDVR0fBHgwdjB0oHKgcIY3aHR0cDovL3Nydi1zdWJjYS0wMS5v
  a2J0c3AuY29ycC9DZXJ0cy9Sb290Q0EtT0tCVFNQLmNybIY1aHR0cDovL3Nydi1z
  dWJjYS0wMS5va2J0c3AuYnkvQ2VydHMvUm9vdENBLU9LQlRTUC5jcmwwgboGCCsG
  AQUFBwEBBIGtMIGqMFQGCCsGAQUFBzAChkhodHRwOi8vc3J2LXN1YmNhLTAxLm9r
  YnRzcC5jb3JwL0NlcnRzQUlBL3Nydi1yb290Y2EtMDFfUm9vdENBLU9LQlRTUC5j
  cnQwUgYIKwYBBQUHMAKGRmh0dHA6Ly9zcnYtc3ViY2EtMDEub2tidHNwLmJ5L0Nl
  cnRzQUlBL3Nydi1yb290Y2EtMDFfUm9vdENBLU9LQlRTUC5jcnQwDQYJKoZIhvcN
  AQENBQADggIBAJEp2DWhXkpCvHLZaEveXSP2wROghoiqkWO1drlDDZfX19b2oHdH
  vYmOkYust9o47qilQLG962Amk25xtpHN8RT8X9EUdFTtgXmDPsYK6heW5ys/CZRC
  cw1UvwZayI9yOo/h2vwJIURf5thwS/5k6gqJLmHkxAIl325juFCKhueOiQS/VlxZ
  a06lpEnDKXqxpZ1oySvmZV53mcx27dEisOyE7S4EEL/4Th6FXQKzni5ojUwJX6g/
  ix9Ox6Fa4FwbFqrV2IHbuYOudBNnZCuDJEQBSMcznx4eepTb/a/e1Gno6zV31Qpg
  3b6537XeMLmh9vOFo3Z88ignjQME7TfnykA1f0r4pWuOzsOtoad42ntoct1XNSd5
  Q1bzIpUjuA0BgIbpoTh4zHnJzfBGIxnpQKp4B26SSHPRh/iw5whviXsPBFDXcnTK
  6nt0w7l2Tsy6cxIVo+ZUlSJ/e4ey9j30+Lq6nexPn5P8eGTGzuh98it2d5OPOUv4
  xycQhD4bBVk8Ls5gCdgj2atSyHR4wnveCfIR1w8G4ooDhbfmhiL7frpZebJe6uRN
  6I2Ce6LlLB24uRJrIZ+RZR0f00WPYpApY+Q+NOShd9MZMikTWusT8NriiLvzeA0+
  CKs7HjA5q0pWQcxwEvA5wvWuU0WOt4tlGAfuAclJF29x3qDN2EBQAM+b
  -----END CERTIFICATE-----
